### ISSUE TITLE
deep-in-thought image links back to the top

### ISSUE THREAD

**Issue by oliverjam** [FAC-11/JAAM#35]
Is there any reason this image is a link? Users won't have got very far down the page at this point, so it's slightly confusing flow to take them back up to where they just were.

**Comment by oliverjam** [comment]
Sorry to re-open @AseelM, but I'm still confused by the latest commit. Why does the image inside the About section now link to the About section? Does the image need to be a link at all?

**Comment by ameliejyc** [comment]
the link has been removed completely now
