### ISSUE TITLE
Accessibility: no indication of focus on inputs

### ISSUE THREAD

**Issue by oliverjam** [FAC-11/JAAM#37]
If I try to navigate your site without using my mouse I have no obvious way of seeing when I have focused the form inputs.

You've set `outline: 0` on all your inputs, which is understandable because the default is kind of ugly, but you really need to replace this so ensure your UI is as accessible as possible. I like to change the border colour when inputs are focused — this is nice even if users are using a mouse just to give a clear indication of which field they're currently filling in.

**Comment by ameliejyc** [comment]
form input now go pink and the border highlights. thanks!
